### ISSUE TITLE
Shipdelight (RSF) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#1222]
### Both the flows can't have the same txn id, message id and timestamp

**/receiver_recon**

- /message/orderbook/orders/0/state should be "Completed"

**/on_receiver_recon**

- /context/domain must be ONDC:NTS10
- /message/orderbook/orders/0/order_recon_status must be 02

@sri-shipdelight

**Comment by sri-shipdelight** [comment]
@bluecypher Feedback has been incorporated. Kindly merge this PR and review - #1235

**Comment by RupalSingla** [comment]
There should be five distinct flows within the order book. For both reciver_recon and on_reciver_recon 

@sri-shipdelight

**Comment by sri-shipdelight** [comment]
@bluecypher @RupalSingla  Feedback has been incorporated. Kindly review - #1256

**Comment by bluecypher** [comment]
- Why is the /receiver_recon called with a delay of many days? (check orderbook created_at and updated_at timestamp)
- Why is there a discrepancy in the counterparty_recon_status for order ID: 31bc89f9-1303-40c5-b8c6-a07786d0134b? Both flows show different statuses.

@sri-shipdelight

**Comment by sri-shipdelight** [comment]
- The delay was caused by the logistics buyer sending a /collector_recon call from his system for an older order instead of creating five new orders for the test case. As a result, there was a discrepancy in the timestamp between the order creation (created_at) and order modification (updated_at) in the orderbook.

- We have only five orders from the buyer side so we are using same orders to show both test cases,

@bluecypher
