### ISSUE TITLE
Mahindra (RSF)- compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/verification-logs#1226]
## FLOW- 1
//reciver_recon

- deduction_by_collector amount is provided in the payload but still buyer_app_finder_fee_amount zero . this needs to get changed

//on_reciver_recon

-  API can't have the same message_id and transaction_id, 
- ttl is missing

@jeevansanju

**Comment by RupalSingla** [comment]
**/receiver_recon**

- /message/orderbook/orders/0/payment/params must have required property 'transaction_status'

**/on_receiver_recon**

- /context/domain must be equal to constant (ONDC:NTS10)

@jeevansanju

**Comment by RupalSingla** [comment]
FLOW- 1
**/on_receiver_recon**

- /message/orderbook/orders/4 must have required property 'settlement_reference_no'

**Comment by bluecypher** [comment]
**/receiver_recon**

- payment/params/transaction_id can't be the same as context/transaction_id

**/on_receiver_recon**

- invalid ttl in /context; ttl is not required in /on_receiver_recon (otherwise should be in valid ISO8601 duration format)
- order_recon_status should be 02

## Flow 2

- invalid correction flow; counterparty_recon_status can't be 01 in case of correction scenario


@jeevansanju

**Comment by bluecypher** [comment]
@jeevansanju, why is there a discrepancy in the counterparty_recon_status for order id: 2023-10-27-390123; both the flows show different status.

**Comment by jeevansanju** [comment]
@bluecypher, We didn't get any buyers for extracting logs so i've used postman with same request Json (changed transaction_Id, message_id and some fields) to hit receiver_recon API and did some manual changes to order price in database, before the correction flow for logs purpose.

**Comment by bluecypher** [comment]
Logs cleared for RSF v1.0.0, pending above change being enabled

@jeevansanju
