### ISSUE TITLE
Plotch Seller App - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#303]
Pls submit logs with a buyer app not from Plotch e.g. Kotak or Mystore or Airpay.

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by vikramacharya** [comment]
@BLR-0118 : Below is the PR for log with Mystore buyerapp

https://github.com/ONDC-Official/verification-logs/pull/324

**Comment by BLR-0118** [comment]
Logs with mystore:
1. /on_search - 
a. many mandatory keys missing e.g. bpp/descriptors.images, bpp/providers.images & symbol;
b. invalid key - "@ondc/org/s": {
							"net_quantity": ""
						},
c. for category_id of packaged foods, all mandatory statutory reqs need to be provided;
d. valid fssai no is 14 digits;
2. /on_select -
a. in quote breakup, item_id should be the same as fulfillment_id for delivery & packing (since these charges are at fulfillment level);
3. fulfillments.tracking was true in /on_select but false in /on_init. Why?
4. Fulfillments block with default state is missing in /on_confirm;
5. Difference of almost 1 hr in timestamp for /status & /on_status. Why?
6. /on_status - value of fulfillment state is actually the code, not name;
7. No support/update API?

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by vikramacharya** [comment]
@BLR-0118 - Please have a look at the updated logs based on the feedback
https://github.com/ONDC-Official/verification-logs/pull/356

We didn't find any option to generate support or update call from the mystore buyer app.

**Comment by BLR-0118** [comment]
1. /on_select - 
- value of selected item in /search is 101 but here it's 100;
- all values should be string;
2. /on_init -
- finder fee type was "percent" in /search, but is "fixed" here;
3. /on_status -
- invalid key: items."tags": {
            "status": "Completed"
          }
4. No /on_support, /on_update APIs?

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by vikramacharya** [comment]
@BLR-0118 : Updated PR is below.
https://github.com/ONDC-Official/verification-logs/pull/359

/on_select - value of selected item in /search is 101 but here it's 100;  - We have updated the price post placing order to test one of the use case. Due to which search was showing the 101 but select was 100.
all values should be string; - Corrected.
/on_init - finder fee type was "percent" in /search, but is "fixed" here; - Resolved.
/on_status - invalid key:  - Removed the values from this key. It will only be populated in case of part cancel or return status update
items."tags": {
"status": "Completed"
}
No /on_support, /on_update APIs - We support, attached PR has the log. Wasn't able to generate from the buyer app earlier.

**Comment by BLR-0118** [comment]
1. /on_search:
- Since category is packaged food, only fill up "@ondc/org/statutory_reqs_prepackaged_food", not "@ondc/org/statutory_reqs_packaged_commodities";
- you can't define both fixed timings:
              "range": {
                "end": "2200",
                "start": "0800"
              },
and variable timings:
                "schedule": {
                  "frequency": "PT4H",
                  "times": [
                    "0800",
                    "1300",
                    "1800"
                  ]
2. /update - 
- cancel doesn't result in reverse qc
- /on_update shows fulfillment_id as "Fulfillment1-ReverseQC" but "fulfillments": []?

**Comment by BLR-0118** [comment]
@vikramacharya

**Comment by vikramacharya** [comment]
@BLR-0118 
Please review the PR https://github.com/ONDC-Official/verification-logs/pull/366/files

1. /on_search:
a) Since category is packaged food, only fill up "@ondc/org/statutory_reqs_prepackaged_food", not "@ondc/org/statutory_reqs_packaged_commodities";  - As discussed this is required.

b) you can't define both fixed timings: - this is fixed. 

/update -
cancel doesn't result in reverse qc - Handled this
/on_update shows fulfillment_id as "Fulfillment1-ReverseQC" but "fulfillments": []? - This will only come for return cases.

**Comment by BLR-0118** [comment]
logs verified & certified for compliance
