### ISSUE TITLE
Esamudaay - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#305]
Logs checked with myStore:
1. /on_search - 
a. circle.radius should also have unit;
b. category_id should be "F&B" or anything else from the list [here](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=647621341)
c. price.listed_price is invalid. You can use price.listed_value instead;
d. what is parent_item_id referring to here?
e. what does return window of 24h mean with returnable = false?
2. /on_select - fulfillment tat of 12hrs doesn't match with immediate delivery;
3. /on_init - billing.updated_at & created_at should be provided;
4. /on_confirm - finder fee amount & withholding amount should be string;

**Comment by BLR-0118** [comment]
No /support, /track, /cancel, /update APIs?

**Comment by BLR-0118** [comment]
@ShishirPrashant

**Comment by ShishirPrashanth** [comment]
All issues have been fixed in https://github.com/ONDC-Official/verification-logs/pull/311

1a - done
1b - done
1c - removed listed_price, not compulsory
1d -parent_item_id refers to product id. It is in the swagger spec but not compulsory. item.id is still present which has our sku id.
1e. removed return window for non returnable items

2. This is a config thing, can be edited anytime. Updated to 1 hour in the updated logs
3. done
4. done

/support, /on_support and /cancel, /on_cancel are available with meesho
With mystore couldn't trigger support. Couldn't trigger status or cancel so did a status update from merchant to show on_status and triggered merchant_cancellation to show on_cancel. 

We don't support /track
We also don't yet support /update

**Comment by BLR-0118** [comment]
1. /on_search -
a. what's the purpose of locations.descriptor when address is provided?
b. circle.radius - only unit specified is km (in Serviceability Construct [here](https://docs.google.com/document/d/1f4QbVstY5m-L_-Jut5jvbeiaBKLR1ttJL_am6GG2Fko/edit))
c. what does item.parent_item_id mean?
d. group buy tags aren't yet approved by ONDC;
e. how to interprete fulfillment_id "3"? One way is if you provide the static values (as shown in API contract);
2. /on_select  - 
a. not sure how to interprete items.quantity? This is supposed to be provided by buyer app so in case the item is out of inventory, what shows here & in breakup?
b. items.quantity was specifically excluded from the API contract. Why is it being included here?
3. /on_confirm - 
a. "@ondc/org/settlement_window":"PT2D" is invalid (should be "P2D");
b. "@ondc/org/settlement_details".tags is invalid;
4. /on_status - order status still shows "Created". How is order acceptance by seller updated through the protocol?

**Comment by BLR-0118** [comment]
@ShishirPrashanth

**Comment by ShishirPrashanth** [comment]
Resolved in https://github.com/ONDC-Official/verification-logs/pull/322

1a - Removed this
1b - Fixed, sending in km
1c - parent_item_id is the product id (part of swagger spec but not compulsory). item.id is sku id.
1d - these won't be available in prod. This has only been enabled for testing with Microsoft in staging and preprod.
1e - bpp/fulfillments has the same id. on_search requests can be quite large so the logger can't print the entire thing. I have updated full response for Meesho this time and a full small response for Mystore.

2a, 2b. Was added for consistenct since quantity is required in on_init and on_confirm. Have removed it from on_select now

3a. Config issue, someone had updated the wrong value in db. fixed.
3b. Minor error, fixed. Removed tags from settlement_details.

4. When seller accepts the order, on_status call is automatically triggered with the state as "Accepted". Pls refer mystore on_status.json for this example.

Please note:
With Meesho: example for bap initiated status and cancel
With Mystore: example for bpp initiated status and cancel

**Comment by ShishirPrashanth** [comment]
@BLR-0118

**Comment by BLR-0118** [comment]
Logs with Meesho:
1. /on_select, /on_init, /on_confirm - tax should be at item level;
2. /on_init - some of the keys in settlement_details will have actual values, right? (not null)
3. Are you planning to provide /on_track, /on_update APIs?

**Comment by BLR-0118** [comment]
@ShishirPrashanth

**Comment by ShishirPrashanth** [comment]
@BLR-0118  For the time being we will be adding tax value to convenience charge and sending in on_select, on_init and on_confirm.

We charge tax on delivery and packing charge as well and that isn't possible when computing at item level. Will need to come up with a better way to handle. Until then we will not send "tax" and instead add the charge as convenience charge.

**Comment by ShishirPrashanth** [comment]
Resolved in https://github.com/ONDC-Official/verification-logs/pull/333:

Removed tax from the spec until we come up with a better way of calculating.
Updated on_select, on_init and on_confirm for Mystore so pls review from that.
Updated on_select and on_init with Meesho since their platform is down and confirm requests are not working from their end.

@BLR-0118

**Comment by BLR-0118** [comment]
Logs cleared for compliance. Can move to Prod N.
