### ISSUE TITLE
Growthfalcons - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#315]
Logs with Kotak / Gogappi:
1. /on_search - store timings can't be both fixed & variable:
fixed part (means store is open 7 days a week from 0000 to 2359):
                            "time": {
                                "range": {
                                    "start": "0000",
                                    "end": "2359"
                                },
                                "days": "1,2,3,4,5,6,7",
variable part: means store opens for 23hrs at a time from 0000 hrs:
                                "schedule": {
                                    "frequency": "PT23H",
                                    "times": [
                                        "0000"
                                    ]
                                }
2. /on_select - 
a. ttl of P1D is too high. Pls note the outer limit is 30s as fixed in the API contract;
b. what does this mean: "@ondc/org/TAT": "P0DT1H30M0S"? 90M can be written as "PT90M", right?
3. No /on_support, /on_cancel, update & /on_update, /on_track APIs?

**Comment by BLR-0118** [comment]
@SandeepGF

**Comment by BLR-0118** [comment]
@SandeepGF @VidyaGF - since you have small no of issues, request you to pls fix & resubmit (preferably only the affected APIs using the same buyer app)

**Comment by BLR-0118** [comment]
Logs with Loadshare:
1. /search - 
a. same issue as 1 above;
b. fulfillment.end.address.area_code is mandatory;
c.             "payment": {
                "collected_by": "BAP",
                "@ondc/org/collection_amount": "0"
            },
Not required for Prepaid (collection_amount reqd for CoD);
2. /init -
a. what's the purpose of having items.price?
b. /search had fulfillment type of prepaid which translates to payment type of on-order. Here, it's changed to post-fulfillment (i.e. CoD);
3. /confirm - no order state?
4. no /support, /update, /cancel, /track APIs?

**Comment by SandeepGF** [comment]
@BLR-0118 
Logs with Kotak / Gogappi:
1. fixed
2a.  fixed.
2b.  "PT90M" is the simplified form of "P0DT1H30M0S" can I retain the same?
3. update we are not supporting

Logs with Loadshare:
1a, 1b, 1c  fixed
2a. fixed
2b. In Search we are saying that the retail order is prepaid so in search we added **type: prepaid** and in init, we are saying the payment to the logistic partner is COD so we added payment_type: POST-FULFILLMENT. is my understanding wrong here?
3. fixed
4. update not implemented

**Comment by BLR-0118** [comment]
1. /on_search - time range (start, end) indicates that store is open 24 hrs. If so, why have the time range at all?
2. /on_select - what does a TAT like P0DT1H30M0S mean? Why not "PT90M"?
3. /on_select - tax has to be at item level, hence item id should also have the id of the product (check API contract on how to define);
4. No tracking APIs (typically used in F&B)?

**Comment by BLR-0118** [comment]
Logs with Loadshare:
1. No /support, /track APIs?

**Comment by BLR-0118** [comment]
@SandeepGF

**Comment by SandeepGF** [comment]
@BLR-0118 , Please find the answers inline below:

**Logs with Gogappi:**

1. /on_search - time range (start, end) indicates that store is open 24 hrs. If so, why have the time range at all?
   **_Ans:  As this is in staging , we did not want buyer apps to get blocked because of store open hours, hence it is kept 24 hours for now. However, in prod N, respective store times will be utilized._**

2. /on_select - what does a TAT like P0DT1H30M0S mean? Why not "PT90M"?
  **_Ans : Standard Python libraries convert to the above format "P0DT1H30M0S" which is semantically correct. Let me know if you think otherwise. Ideally , this should be still processed. The same is  being used with payTM in prod N-1._**

4.  No tracking APIs (typically used in F&B)?
 _**Ans :  We have the /track and /on_track with Loadshare , added in the link given below. However, with Gogappi we don't see track enabled. Hence, same couldn't be shared.**_
 
**Logs with Loadshare:**

No /support, /track APIs?
**_Ans : /support not currently available with Loadshare , as confirmed by @Poornima-Aithal . 
/track already submitted. Resharing the link below_** 

**_Link for track API :_**
https://github.com/ONDC-Official/verification-logs/blob/main/logs/GrowthFalcons/gogappi-growthfalcons-loadshare/growthfalcons-loadshare/track.json

**Comment by BLR-0118** [comment]
ok, thx for the clarification

**Comment by BLR-0118** [comment]
pls proceed with onboarding to prod N
@SandeepGF
