### ISSUE TITLE
Marico - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/verification-logs#393]
1. Pls submit logs with one of the buyer apps that will be in Production e.g. Mystore, Plotch, Airpay, etc.
2. There is an issue with the timestamp (format is correct but your timestamp is not in UTC, check the difference between Context.timestamp in /search and /on_search)
3. Please make sure your payloads are exactly compliant with the API contract [here](https://docs.google.com/document/d/12oMC4A05jT5rjCbY-M7j4T2oekr9bqcvSOpTI0jFEgE/edit)

**Comment by BLR-0118** [comment]
@pgandroid1289

**Comment by bluecypher** [comment]
APIs should comply with API contract and logs should be shared as per the [test case scenarios](https://docs.google.com/document/d/1ttixilM-I6dutEdHL10uzqRFd8RcJlEO_9wBUijtdDc/edit).

**/on_search**
City code mismatches in /search and /on_search
timestamp difference b/w search and on_search is more than 30s
bpp/categories is not a valid key as per the API Contract
bpp/descriptor code is not a valid key
merchant's contact details missing in bpp/providers.fulfillments (all other attributes are invalid)
serviceability construct is not defined.
provider enable/disable should be explicitly defined.
store timings, items count are not present
enhanced taxonomy should be referred for category_id

**/select**
Timestamp for /on_search api cannot be greater than or equal to /select api
fulfillments location.gps and area_code can't be null

**/on_select**
City code mismatch in /search and /on_select
Pre-order fulfillment state codes should be used in fulfillments[]
quote.price.value 229 does not match with the price breakup 5

**/init**
Timestamp for /on_select api cannot be greater than or equal to /init api
billing.address.door is deprecated key
payment object is not as per the API contract

**/on_init**
payment settlement details are not present

**/confirm**
City code mismatch in /search and /confirm
Timestamp for /on_init api cannot be greater than or equal to /confirm api
Billing object mismatches in /init and /confirm
payment settlement_details mismatch in /on_init & /confirm
order.created_at timestamp should be the same as context.timestamp
Quote Objects in /on_select and /confirm do not match
Quoted Price in /confirm INR 229 does not match with the quoted price in /on_select INR 5

**/on_confirm**
1 is not of type 'string' in items[0].fulfillment_id
'@ondc/org/settlement_details' is a required property in payment
fulfillment is an invalid object name (should be fulfillments)
default fulfillments state code is missing
City code mismatch in /search and /on_confirm
order.created_at timestamp mismatches in /confirm and /on_confirm
Billing object mismatches in /init and /on_confirm
Quote Object in /on_select and /on_confirm do not match

/on_cancel
'fulfillments' is a required property in $
City code mismatch in /search and /on_cancel

**/status**
City code mismatch in /search and /status

**/on_status**
'fulfillment_id' is a required property in $.items[0]
'currency' is a required property in $.payment.params
'fulfillments' is a required property in $
Provider Id mismatches in /on_search and /on_status
linked_orders is not a part of retail API contract
order created_at and updated_at timestamps should conform to order's state


@pgandroid1289

**Comment by bluecypher** [comment]
### Flow 1

**/search**

- No /search API to validate

**/on_search**

- bpp/providers[].time.timestamp should match context.timestamp
- /message/catalog/bpp/providers/0/@ondc/org/fssai_license_no must NOT have fewer than 14 characters
- either one of fixed or split timings for store should be provided
- /message/catalog/bpp/providers/0/items/0/quantity/maximum/count must be string
- /message/catalog/bpp/providers/0/items/0/quantity/available/count must be string
- /message/catalog/bpp/providers/0/items/0/category_id must be equal to one of the allowed values (Fruits and Vegetables,Masala & Seasoning,Oil & Ghee,Gourmet & World Foods,Foodgrains,Eggs, Meat & Fish,Cleaning & Household,Beverages,Beauty & Hygiene,Bakery, Cakes & Dairy,Kitchen Accessories,Baby Care,Snacks & Branded Foods,Pet Care,Stationery,Continental,Middle Eastern,North Indian,Pan-Asian,Regional Indian,South Indian,Tex-Mexican,World Cuisines,Healthy Food,Fast Food,Desserts,Bakes & Cakes,Beverages (MTO),Home Decor,Home Furnishings,Furniture,Garden and Outdoor Products,Home Improvement,Cookware and Dining,Storage and Organisation)
- /message/catalog/bpp/providers/0/items/0/price/value must be string
- /message/catalog/bpp/providers/0/items/0/price/maximum_value must be string
- /message/catalog/bpp/providers/0/items/0/price/listed_price is invalid key
- /message/catalog/bpp/providers/0/items/0 matched is invalid key
  contact_details_consumer_care should be in the format "name,email,contact-no"
- /message/catalog/bpp/providers/0/items/0/@ondc/org/statutory_reqs_packaged_commodities must have required property 'common_or_generic_name_of_commodity'
- /message/catalog/bpp/providers/0/items/0/@ondc/org/statutory_reqs_packaged_commodities must have required property 'month_year_of_manufacture_packing_import'
- /message/catalog/bpp/providers/0/items/0/@ondc/org/statutory_reqs_packaged_commodities/manufacturer_or_packer_name must not be empty
- /message/catalog/bpp/providers/0/items/0/@ondc/org/statutory_reqs_packaged_commodities/net_quantity_or_measure_of_commodity_in_pkg must match not be empty

**/select**

- /context must have required property 'bpp_uri'
- /context must have required property 'ttl'

**/on_select**

- /fulfillments/0/@ondc/org/category must be equal to one of the allowed values (Express Delivery,Standard Delivery,Immediate Delivery,Same Day Delivery,Next Day Delivery)
- "@ondc/org/TAT" (O2D) can't be greater than time_to_ship (O2S) in /on_search
- Timestamp for /select api cannot be equal to /on_select api

**/init**

- /context must have required property 'bpp_uri'
- /context must have required property 'ttl'
- /message/order/billing/address/street is invalid key
- /message/order/billing/address/locality must be string
- /message/order/fulfillments/0/end/location/address/locality must be string
- /message/order/fulfillments/0/end/location/address/street is invalid key
- billing.created_at should match context.timestamp
- billing.updated_at should match context.timestamp

**/on_init**

- /billing/address must have required property 'building'
- /billing/address/locality must be string
- /fulfillments/0/end/location/address must have required property 'building'
- /fulfillments/0/end/location/address/locality must be string
- /quote must have required property 'ttl'
- /payment/@ondc/org/settlement_details/0/settlement_type must be equal to one of the allowed values (upi,neft,rtgs)
- Timestamp for init api cannot be greater than or equal to on_init api
- Billing object mismatches in /init and /on_init
- items' unit price missing in quote object

**/confirm**

- /context must have required property 'bpp_uri'
- /context must have required property 'ttl'
- /message/order must have required property 'state'
- /message/order/billing/address must have required property 'building'
- /message/order/billing/address/locality must be string
- /message/order/fulfillments/0 must have required property 'tracking'
- /message/order/fulfillments/0/end/location/address must have required property 'building'
- /message/order/fulfillments/0/end/location/address/locality must be string
- /message/order/quote must have required property 'ttl'
- /message/order/payment/@ondc/org/settlement_details/0/settlement_type must be equal to one of the allowed values (upi,neft,rtgs)
- Billing object mismatches in /init and /confirm
- order.created_at timestamp should match context.timestamp
- order.updated_at timestamp should match order.created_at timestamp
- discrepanices between quote objects in /on_select and /confirm
- Buyer App Finder fee can't change

**/on_confirm**

- /billing/address must have required property 'building'
- /fulfillments/0 must have required property '@ondc/org/provider_name'
- /fulfillments/0 must have required property 'state'
- /fulfillments/0/start/location must have required property 'id'
- /fulfillments/0/start/location must have required property 'descriptor'
- /fulfillments/0/end/location/address must have required property 'building'
- /payment/@ondc/org/settlement_details/0/settlement_type must be equal to one of the allowed values (upi,neft,rtgs)
- Timestamp for /confirm api cannot be greater than or equal to /on_confirm api
- Order Id mismatches in /confirm and /on_confirm
- fulfillments[] start and end time range can't be same
- payment object mismatches in /confirm and /on_confirm
- payment.params.transaction_id can't change in /on_confirm
- order.created_at timestamp mismatches in /confirm and /on_confirm
- Billing object mismatches in /init and /on_confirm
- discrepanices between quote objects in /on_select and /on_confirm
- Buyer app finder fee can't change in /on_confirm

**/on_status (delivered)**

- /billing/address must have required property 'building'
- /fulfillments/0/start/location must have required property 'id'
- /fulfillments/0/start/location must have required property 'descriptor'
- /fulfillments/0/end/location/address must have required property 'building'
- /quote/breakup/0 must have required property '@ondc/org/title_type'
- /quote/breakup/0 must have required property '@ondc/org/item_id'
- /quote/breakup/1 must have required property '@ondc/org/title_type'
- /quote/breakup/1 must have required property '@ondc/org/item_id'
- /payment/@ondc/org/settlement_details/0/settlement_type must be equal to one of the allowed values (upi,neft,rtgs)
- tags is not required
- Order id in /confirm and /on_status do not match
- invoice document is missing

**/update**
No /update api to cover return flow

### Flow 2 (Not as per the API Contract)

In case of change of delivery address, a new /select call should be initiated

**/on_cancel**
No /on_cancel api to validate

### Flow 3 (Not as per the API Contract)

No return flow

### Flow 4 (Not as per the API Contract)

**/on_select**
Suitable domain error should be provided when item quantity is unavailable

### Flow 5 (Not as per the API Contract)

Out of stock scenario not covered

**/on_cancel**
No on_cancel api to validate


@pgandroid1289

**Comment by bluecypher** [comment]
## Flow 1

**/on_search**

- /message/catalog/bpp/providers/locations/time must have required property 'schedule' (for holidays)
- context.timestamp for /on_search can't be equal to the /search api

**/on_select**

- context.timestamp difference b/w /select and /on_select can't be greater than ttl
- fulfillments TAT (O2D) can't be smaller than time_to_ship in /on_search (O2S)

**/on_init**

- /quote must have required property 'ttl'
- context.timestamp for /on_init can't be equal to the /init api
- billing.address.door is an invalid key
- Buyer app finder fee can't change in /on_init
- unit price of item missing in quote.breakup (item.price)

**/on_confirm**

- /billing/address must have required property 'building'
- /fulfillments/0 must have required property '@ondc/org/provider_name'
- /fulfillments/0 must have required property 'state'
- /fulfillments/0/start/location must have required property 'id'
- /fulfillments/0/start/location must have required property 'descriptor'
- /fulfillments/0/end/location/address must have required property 'building'
- context.timestamp for /on_confirm can't be equal to the /confirm api
- Order Id mismatches in /confirm and /on_confirm
- order.updated_at timestamp should be updated as per the context.timestamp (since default fulfillment state is added)
- Buyer app finder fee can't change in /on_init
- payment uri and tl_method are invalid keys
- payment.params.transaction_id mismatches in /confirm and /on_confirm

**/on_status (completed)**

- billing created_at and updated_at timestamps can't change in /on_status
- fulfillments start and end time.timestamp should match the context.timestamp
- order.created_at should be the same as /confirm timestamp
- order.updated_at should be updated as the context.timestamp

**No /update and /on_update to cover return flow**

## Flow 2

- similar issues as Flow 1

**on_status (after seller cancel)**

- cancellation_reason_id is missing in tags

## Flow 3

- similar issues as Flow 1

**No /update and /on_update to cover return flow**

## Flow 4

- similar issues as Flow 1

**No /update and /on_update to cover return flow**

## Flow 5

- similar issues as Flow 1


@pgandroid1289

**Comment by abhinavv245** [comment]
## Flow 1
- context.timestamp difference between /action and /on_action cannot be greater 30 seconds(ideally <5s).

**/on_search**
- /message/catalog/bpp/providers/items/category_id must be equal to one of the non deprecated categories [enhanced sub-category list](https://docs.google.com/spreadsheets/d/1ayRbp-WmXwwbzp7z1MgRO0NuKZM1AQk4GGZ8SE4NTnw/edit#gid=0)


**/on_select**
- Timestamp for /select api cannot be equal to /on_select api


**/on_init**
- /quote must have required property 'ttl'
- Billing object mismatches in /init and /on_init
(created_at,updated_at timestamps are different)


**/on_confirm**
- order.created_at timestamp mismatches in /confirm and /on_confirm
- order.updated_at timestamp should be updated as per the context.timestamp (since default fulfillment state is added)
- Billing object mismatches in /confirm and /on_confirm
(created_at,updated_at timestamps are different)
- payment object mismatches in /confirm & /on_confirm
(payment.params.transaction_id should be same)


**/on_status**
- If fulfillment state is Pending, start.timestamp and end.timestamp are not required.
- Timestamp for /status api cannot be equal to /on_status api
- order.created_at timestamp cannot be greater than order.updated_at

**/on_update**
- "Completed" is not a valid fulfillment state( Should be "Order-delivered").
- /quote must have required property 'ttl'
- Timestamp for /update api cannot be equal to /on_update api


## Flow 2
- Similar issues as Flow 1

**/on_status**(after seller cancel)
- cancellation reason id missing in /order/tags

## Flow 3
- Similar issues as Flow 1

## Flow 4

**/on_select**
- "@ondc/org/item_quantity" can't be 0 when item is available (item.quantity.available.count is not 0).

**/on_update** (return_approved)
- New fulfillment should be created for Reverse QC for item id "8901088055772".

## Flow 5
- Similar issues as above flows

@pgandroid1289

**Comment by abhinavv245** [comment]
## Flow 1

- order.created_at timestamp cannot be greater than order.updated_at
- ttl should not present for /on_action apis 

**on_search**

- /items/time_to_ship (O2S) cannot be 30 seconds.

**/on_select**

- context.action should be on_select
- delivery charges line item should be present in quote.breakup
- @ondc/org/TAT (O2D) should be greater time to ship in /on_search

**/on_init**

- Discrepancies between the quote object in /on_select and /on_init
(unit price missing in quote.breakup)

**/on_confirm**

- order.created_at timestamp mismatches in /confirm and /on_confirm
- order.updated_at timestamp should be updated as per the context.timestamp (since default fulfillment state is added)
- Billing object mismatches in /confirm and /on_confirm
(created_at,updated_at timestamps are different)
- payment object mismatches in /confirm & /on_confirm
(payment.params.transaction_id should be same)

**on_status**

- Invalid payload, item should not be liquidated when the order is not delivered.
- Invalid key "fullfillmentEndTimeJson" in /fulfillments/end
- Invalid key "fullfillmentStartTimeJson" in /fulfillments/start 

**on_update** 

- pickup and delivery time cannot change in /on_update

**on_update** (liquidated)

- context.city cannot change in /on_update
- message_id for all unsolicited /on_update should be same as /update (temporarily)
- context.city, context.bap_id cannot change in /on_update
- context.action should be on_update
- quote should be updated on liquidated state
- "Completed" is not a valid fulfillment state

## Flow 2 

- Similar issues as Flow 1

**on_select**

- Fulfillment state should be non serviceable in case of domain error

## Flow 3 

- Similar issues as Flow 1

## Flow 4

- Similar issues as Flow 1

**on_update**

- For liquidated item status, quote price should be updated.

## Flow 5

- Similar issues as above flows

**on_cancel**

- context.timestamp cannot be same as in /cancel  

@pgandroid1289

**Comment by abhinavv245** [comment]
## Flow 1

**/on_search**

- /bpp/providers/time/timestamp should be in RFC339 format and should match context.timestamp

**/on_init**

- item available count and maximum count not required in quote.breakup
- /fulfillments/end/location/address/door is not required


**/on_confirm**

- order.updated_at timestamp should be updated as per the context.timestamp (since default fulfillment state is added)


**/on_status** (completed)

- fulfillments.start.time.timestamp cannot be future dated from the context.timestamp
- fulfillments.end.time.timestamp should match context.timestamp and cannot be future dated
- order.created_at timestamp cannot change in /on_status
- order.updated_at timestamp should be updated as per the context.timestamp
- billing.created_at and billing.updated_at timestamps cannot change in /on_status
- delivery line item (delivery charge) is missing in quote.breakup

**/on_update** (both)

- order.created_at timestamp cannot change in /on_update
- pickup and delivery time cannot change in /on_update
- message_id for all unsolicited /on_update should be same as /update (temporarily)


## Flow 2

- Similar issues as flow 1

**/on_status**

- order and fulfillment state should be cancelled since order is already cancelled by the seller

##  Flow 3 , Flow 4 and Flow 5

- Similar issues as flow 1

@pgandroid1289

**Comment by abhinavv245** [comment]
## Flow 1


**/on_search**
- /message/catalog/bpp/providers/items must have required property '@ondc/org/fssai_license_no'
- /message/catalog/bpp/providers/items must have required property '@ondc/org/statutory_reqs_prepackaged_food' ( for Snacks & Branded Foods)
- /message/catalog/bpp/providers/items must have required property 'tags'
- store enable/disable timestamp (/bpp/providers/time/timestamp) must match context/timestamp
- end time cannot be '2400' in /locations/time/range (should be 2359)

**/on_confirm**
- delivery line item (delivery charge) missing in quote.breakup

**/on_status**
- pickup (fulfillments/start/time/timestamp)and delivery(fulfillments/end/time/timestamp) time cannot be same for fulfillment state "Order delivered"
- order.created_at timestamp cannot change in /on_status
- billing.created_at and billing.updated_at timestamps cannot change in /on_status

**/on_update**
- liquidated item should be present in quote.breakup
- order.created_at timestamp cannot change in /on_update

## Flow 2

- Similar issues as Flow 1

**on_status**
- order state cannot be "Accepted" after the order has been cancelled by the seller

## Flow 3

- Similar issues as Flow 1

**on_update**
- pickup(fulfillments/start/time/timestamp) and delivery(fulfillments/end/time/timestamp) time cannot change after the order is delivered

## Flow 4

- Similar issues as Flow 1

**on_status** 
- order.created at cannot change in /on_status
@pgandroid1289

**Comment by abhinavv245** [comment]
## Flow 1

**/on_search**
- tracking is not required in bpp/fulfillments in /on_search API

**/on_status(both)**
- order.created_at timestamp cannot change in /on_status
- /fulfillments/end/time/timestamp (delivery time) cannot be future dated and should match the context.timestamp 
- billing.created_at and billing.updated_at timestamps cannot change in /on_status

**/on_update**
- order.created_at timestamp cannot change in /on_update
- delivery line item is missing
- pickup(fulfillments/start/time/timestamp) and delivery(fulfillments/end/time/timestamp) time cannot change in /on_update and both cannot be same.
- quote.price and quote.breakup should not change for 'Return_Initiated'
- liquidated item should be present in quote.breakup with item price 0 

## Flow 2

- similar issues as Flow 1

**/on_cancel(unsolicited by seller)**
- context.timestamp cannot be same as in /on_confirm

**/on_status(after seller cancelled)**
- pickup(fulfillments/start/time/timestamp) and delivery(fulfillments/end/time/timestamp) timestamps cannot be provided if the order has been cancelled.

## Flow 3

- similar issues as Flow 1

**/on_status(after completion)**
- pickup and delivery time cannot be same for fulfillment state 'Order-delivered'
- billing.created_at and billing.updated_at timestamps cannot change in /on_status

**/on_update**
- all the items should be present in /items

**/on_update(return rejected)**
- message_id for all unsolicited /on_update should be same as /update (temporarily) 

## Flow 4

- similar issues as Flow 1

## Flow 5

- similar issues as Flow 1

@pgandroid1289

**Comment by abhinavv245** [comment]
## Flow 1

**/on_update (liquidated)**
- liquidated item's price should be 0 instead of item's unit price in quote.breakup

## Flow 3

- similar issues as Flow 1

**on_status (completed)**
- delivery(fulfillments/end/time/timestamp) time should be updated as per context.timestamp for fulfillment state is 'Order-delivered'
- billing.created_at and billing.updated_at timestamps cannot change in /on_status
- order.updated_at should be updated as per context.timestamp

**/on_update**
- return can be initiated only after the order has been delivered

## Flow 4

- similar issues as Flow 1

**/on_select (error)**
- '@ondc/org/item_quantity' count should be updated as per the quantity.available.count (quote price should be updated accordingly)

**on_update (liquidated)**
- delivery line item is missing in quote.breakup
- delivery(fulfillments/end/time/timestamp) time cannot change in /on_update

## Flow 5

- similar issues as Flow 4, Flow 1

@pgandroid1289

**Comment by DSVedantRathore** [comment]
Hi @bluecypher, any update on the new logs submitted on Friday?

**Comment by abhinavv245** [comment]
## Flow 3

**/on_status (completed)**

- pickup time (fulfillments/start/time/timestamp) cannot be after the delivery time (fulfillments/end/time/timestamp)


**/on_update**

- context.timestamp cannot be equal to /update context.timestamp

## Flow 4

**/on_select (both)**

- @ondc/org/item_quantity/count is different in /select for item id: MANS108
- '@ondc/org/item_quantity' count should be updated as per the quantity.available.count (only for the item whose selected quantity is not available)
- quote.price.value does not match with the price breakup 

**on_status (both)**
- billing.created_at and billing.updated_at timestamps cannot change in /on_status

**/on_update**

- context.timestamp cannot be equal to /update context.timestamp

## Flow 5

- similar issues as Flow 4

@pgandroid1289 @DSVedantRathore

**Comment by DSVedantRathore** [comment]
Hi @abhinavv245, any update by when we should expect a revert on #732 ?

**Comment by jbjetbro** [comment]
@abhinavv245
@bluecypher please review https://github.com/ONDC-Official/verification-logs/pull/735

**Comment by abhinavv245** [comment]
## Flow 1, Flow 3, Flow 4

**/on_confirm**

-  order.updated_at timestamp should be updated as per the context.timestamp (as default fulfillment state is added)

@pgandroid1289 @DSVedantRathore

**Comment by jbjetbro** [comment]
@abhinavv245
@bluecypher please review https://github.com/ONDC-Official/verification-logs/pull/736

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search: 
- country of origin should be added as per advisory issued yesterday (updated in v1.1.0 API Contract);
- one of the images points to esamudaay.com (cut & paste?);
3. /on_select:
- TAT of 4 days and time to ship is 1 day => ship to delivery is 3 days. Is this really express delivery (ship by air)?
4. /init:
- building.locality is mandatory but not provided; hence, the address is invalid & should have been NACK'd by seller app;
5. /on_status:
- /on_confirm showed total price & payment colllected as 908 but shows as 0 here?
6. /on_update_liquidated:
- should have same message_id as /update;
- how is unit price of 589 * qty of 1 = total price of 0?

Flow 2
====
1. /on_cancel uses same message_id as /on_confirm?
2. /on_select: curious how this is non-serviceable when serviceability is defined as pan-India?

**Comment by BLR-0118** [comment]
All logs to be resubmitted
@jbjetbro

**Comment by jbjetbro** [comment]
@abhinavv245
@bluecypher 
when seller approved buyer return request then in on_update_liquidated breakup price value passed 0 or item price? because when i passed 0 then i got feedback like "how is unit price of 589 * qty of 1 = total price of 0?"

**Comment by jbjetbro** [comment]
@abhinavv245 @bluecypher  please review https://github.com/ONDC-Official/verification-logs/pull/753

For /on_select: curious how this is non-serviceable when serviceability is defined as pan-India?
Yes, we deliver pan-India. However, for the purpose of creating a test scenario, we have temporarily disabled service in that specific pincode.

**Comment by bluecypher** [comment]
- why is there inconsistency in delivery location?
   - /on_init- all the attributes and their values were present
   - /on_confirm - optional attribute door is added with empty value
   - /on_status - the value of locality is removed

- Why is the billing object changed in /on_status? (door is added and value of locality is removed)

- Is the unsolicited "on_status" implemented, and if so, why are fulfillment state updates not sent through unsolicited "/on_status" calls

@jbjetbro

**Comment by jbjetbro** [comment]
@bluecypher @abhinavv245 please review https://github.com/ONDC-Official/verification-logs/pull/757

**Comment by BLR-0118** [comment]
@jbjetbro

**Comment by jbjetbro** [comment]
@BLR-0118  could you please explain the issue with the statement "couldn't figure out whether the pickup time was correctly recorded"? I have checked the logs for flow1, and it appears that the dispatched start time is consistent throughout the context and subsequent status updates. Therefore, I am unable to identify what might be wrong in this case. Can you provide more information or clarify your concerns?

**Comment by jbjetbro** [comment]
@bluecypher @abhinavv245 @BLR-0118 please review https://github.com/ONDC-Official/verification-logs/pull/771

**Comment by DSVedantRathore** [comment]
@bluecypher @BLR-0118 any update on #771? By when can we expect feedback here?

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- pincode based serviceability not supported by any buyer app today. Pls use hyperlocal (radius-based) or pan-India for now;
2. /on_select:
- quote ttl is 30 sec here and 33 secs later in /on_confirm same quote is given with ttl of 30s. In that case, why not have a larger value for quote ttl, so buyer apps can easily optimize?
3. /on_confirm:
- fulfillment TAT in /on_select is 4 days but difference between fulfillment start & end time slots is 2 days?

**Comment by BLR-0118** [comment]
@DSVedantRathore

**Comment by sharva** [comment]
@BLR-0118 

1. /on_search
We used Pan-India before, however in your comments in couple of feedbacks back, you asked us if we are serving pan-india how come a pin code is not serviceable. 

We do serve pan india, but not all pincodes listed on India Post. The list of servicable pincodes are based on our logistics team internally. We say pan india, as we are serving almost all states in India (i.e. we have at least 1 pincode servicable in most states of India)

After your previous feedback, we reached out to Sandeep, and he suggested us to use serviceability type 11 and send pincode range as we have done.

After your latest feedback, we have reached out to Sandeep and he has suggested to go back to Pan India. However note not all pincodes from IndiaPost may be deliverable. Also, test scenarios for submitting this log has a flow that mandatory requires a pincode to be not servicable.

2. /on_select
We have updated it to 24 hours

3. /on_confirm

TAT is 4 days, the product dispatch would be in 2 days (fulfillment start time) and product delivery would be in 4 days (fulfilment end time). Thats why we have TAT 4 days and difference between start and end time be 2 days

---

We will be resubmitting our logs based on above comments, do let us know if it's okay.

@DSVedantRathore @bluecypher

**Comment by DSVedantRathore** [comment]
@bluecypher @BLR-0118 do we need to resubmit the logs now? The only change is to revert back to the previous serviceability logic. Can we move forward without another round of logs?

**Comment by jbjetbro** [comment]
@bluecypher @abhinavv245 @BLR-0118 please review https://github.com/ONDC-Official/verification-logs/pull/791

**Comment by DSVedantRathore** [comment]
@bluecypher @BLR-0118 any update here?

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_select:
- TAT is 4 days. Since time to ship is 1 day & there are 2 items, it can be assumed that both can be shipped in 1 day. This means, it takes 3 days to ship from start to end. However, the fulfillment start time range is 2 days after the order is confirmed. What's the logic here?
2. /on_status - invoice should be added only when fulfillment state is "Order-picked-up";
3. /on_update - timestamp is earlier than update. How?

@DSVedantRathore

**Comment by BLR-0118** [comment]
Pls resubmit logs only for flow 1 addressing these issues

**Comment by jbjetbro** [comment]
@BLR-0118 please review https://github.com/ONDC-Official/verification-logs/pull/810

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- for some catalog items e.g. MANS202, return_window, which is mandatory key, is missing;
2. Why is there a difference in fulfillment.end.location.address between /on_update (which is same as what was passed in /init) and /on_update_liquidated & all /on_status APIs?

**Comment by BLR-0118** [comment]
@DSVedantRathore

**Comment by jbjetbro** [comment]
@BLR-0118 please review https://github.com/ONDC-Official/verification-logs/pull/828. Flow 1 is resubmit.
