### ISSUE TITLE
Signcatch B2B - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#592]
**/search**

- payment.type should be ON-FULFILLMENT as per the MVP doc

**/on_search**

- locations[] city code and name should be mapped correctly
- manufacturer.contact.phone should be either 10 or 11 digits
- payment_ids should be ["2"] for "ON-FULFILLMENT"
- price slabs should not overlap with each other

**/select**

- For MVP, payment type should be "ON-FULFILLMENT"

**/on_select**

- time_to_ship (O2S) in tags (/on_search) can't be greater than @ondc/org/TAT in /on_select

**/on_select (non-serviceable/out-of-stock)**

- error code should be defined outside message

**/init**

- context.city can't change in /init

**/on_init**

- @ondc/org/settlement_details in payment object is not required in case of CoD (will be shared by buyer app in /confirm)

**/confirm**

- payment.settlement_counterparty should be buyer-app (for CoD)

**/on_status**

- /items/tags/status is not required when items' fulfillment is Pending

@SignCatch-NP

**Comment by bluecypher** [comment]
@SignCatch-NP 

Please resubmit the logs as per the [test case scenarios](https://docs.google.com/document/d/1ew9a4AzWgwFHcGqRmnv4XT_oRzHC4Qsl/edit) (Flow Wise)

**Comment by bluecypher** [comment]
## Flow 1

context.ttl = PT30S as per the API Contract

**/on_search**
- /locations/gps and cancellation_terms/return_policy/return_location/gps must have minimum 6 decimal precision

**/select**

- context/domain should be the nic code (nic2004:52110) from /select onwards
- context/core_version should be 1.1.0 from /select onwards

**/on_select**

- @ondc/org/TAT (O2D) can't be equal to time_to_ship (O2S) in /on_search

**/init**
- billing created_at and updated_at should match context.timestamp
- area_code in /fulfillments/end/location/address mismatch in /select & /init (for same gps coordinates)

**/on_init**

- billing object mismatches in /init and /on_init (tax_number is missing)

**/on_confirm**
- order.updated_at timestamp should be updated as per the context.timestamp (since default fulfillment state is added)

**/on_status Order-picked-up**

- fulfillments/start/time/timestamp (pickup time) and order/updated_at must match context/timestamp

**/on_status Out-for-delivery**

- fulfillments/start/time/timestamp (pickup time) should remain same as in /on_status (Order-picked-up)

**/on_status Order-delivered**

- fulfillments/end/time/timestamp (delivery time) and order/updated_at must match context/timestamnp
- payment/params/transaction_id missing

## Flow 2

- similar issues as Flow 1

## Flow 3

- similar issues as Flow 1
- a new /select should be called if there is a change in delivery address

## Flow 5

- similar issues as Flow 1

**/on_select out-of-stock**

- @ondc/org/item_quantity of item: 4548 can't be 0 if the item is available in inventory (available/count and maximum/count are not 0)

@SignCatch-NP

**Comment by bluecypher** [comment]
## Flow 2

**/on_select Non-serviceable**

- delivery charge should not be present when location is not serviceable


@SignCatch-NP

**Comment by BLR-0118** [comment]
Signcatch buyer app with rapidor seller app
============================
Flow 1:
1. /search:
- shows bap_id of rapidor and /on_search shows bpp_id of signcatch (so this is rapidor buyer +signcatch seller)?
- what is the reverse geocoding logic of buyer app? (lat/lng for fulfillment.stops maps to pin 442301 but shows 110056 in logs);
2. /on_search:
- fulfillment type "Pickup" is invalid;
- provider code of "*" is not valid (can be same as id);
- instead of 1000 km serviceability, why not use pan India (radius should only be used for hyperlocal serviceability);
- item.descriptor.code should be as per the format added to API contract;
3. ttl for quote is P1D in /on_select & /on_init but P2D in /on_confirm?

Are there logs for signcatch seller?
@SignCatch-NP

**Comment by BLR-0118** [comment]
Pls recheck your logs. /search shows /select payload and all version nos are 2.0.0 which isn't correct.
@SignCatch-NP @rapidor

**Comment by BLR-0118** [comment]
Signcatch buyer app + Rapidor seller app:
1. /search - reverse geocode of 28.5368099,77.1403572 shows pin code of 110070 but here it's 110057. Is this accurate?
2. /on_search:
- reverse geocoding of 27.071521,75.798846 shows pin code of 302013 instead of 302022 here. Is this accurate?
- item (Lakshmi Bhog Atta 10 kg) should have quantity.unitized.measure.unit of "kilogram" and value of "10", right? (updated UOMs are [here](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/grocery/RET10-UOM.json)). What does 100 units here mean?
- why is manufacturer empty?
- no item descriptor code?
3. /on_init:
- provider_location.id should be "L1", not "F1";
- buyer finder fee was 3% in /search but is 0 percent here;
4. /confirm:
- following keys are invalid: items.price, items.mrp, items.unit, items.returnable. Pls ensure compliance with API contract v1.1;
- buyer finder fee was 3% in search, is 0% here;
5. /on_status:
- invoice should be updated when fulfillment state is "Order-picked-up";

**Comment by BLR-0118** [comment]
@SignCatch-NP @rapidor

**Comment by BLR-0118** [comment]
Rapidor buyer + Signcatch seller:
1. /search:
- Context.city should be the city of end fulfillment, in this case "std:011" (Signcatch buyer app has done it correctly);
2. /on_search:
- item.descriptor.code should be as per format in the API contract;
- "Organic Diet Arhar Dal 500gm" should have quantity.unitized.measure.unit of "gram" and value of "500";
- parent_item_id to be used for variants & no variants are defined here?
3. /on_status (Order-pickup):
- uses same message_id as /on_confirm;
- same issue with /on_status (Out-for-delivery), /on_status (Order-delivered);

**Comment by BLR-0118** [comment]
@SignCatch-NP @rapidor

**Comment by BLR-0118** [comment]
Rapidor buyer app
============
1. /init: locality in location.address should actually refer to locality & not city;

Rapidor seller app
============
1. /on_search: 
- use correct UOM & value from quantity.unitized.measure e.g. ITM05611 should have quantity.unitized.measure.unit of "kilogram" and quantity.unitized.measure.value of "1" (enums are [here](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/grocery/RET10-UOM.json));
- mismatch between gps coordinates & pin code for merchant (is this hardcoded as the buyer app logic looked ok);
2. /on_status: pickup time is updated in "Out-for-delivery" but should also be updated at "Order-picked-up" fulfillment state;

Signcatch buyer app
=============
1. Check your reverse geocoding logic - the search gps coordinates maps to pin code which seems far away from what I see using reverse geocoding tools;
2. Are you supporting pin code based serviceability?

Signcatch seller app
=============
1. /on_select: didn't see tax line items in quote; hope you support it;

**Comment by BLR-0118** [comment]
@SignCatch-NP @rapidor

**Comment by BLR-0118** [comment]
@SignCatch-NP
