### ISSUE TITLE
Rapidor B2B - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/verification-logs#594]
context.ttl should be PT30S as per the API contract
timestamp for the action and corresponding callback APIs can't be the same

**/search**

- search API is not as per the API contract for B2B (fulfillment stops and buyer id are missing)

**/on_search**

- bpp/providers, bpp/fulfillments are not the part of B2B contract
- payments ids can't be same for different types of payments
- ON-FULFILLMENT is missing in payments.type

**/select**

- /message/order/items/ must have required property 'location_id'
- payment is missing (for ON-FULFILLMENT in B2B)
- buyer id is missing

**/on_select**

- context.action should be on_select
- /quote/breakup/0/item/quantity/maximum/count must be string
- /quote/breakup/0/item/quantity/available/count must be string
- /fulfillments/0/tracking must be boolean
- /fulfillments/0/@ondc/org/TAT must match ISO-8601 "duration" format
- /fulfillments/0/state/descriptor/code must be equal to one of the allowed values (Serviceable,Non-serviceable)
- Timestamp for /select api cannot be equal to the /on_select api
- tax breakup into cgst, sgst is not as per the API contract

**/init**

- billing.tax_number is missing
- /billing/address must have required property 'country'
- /billing/email must match format "email"
- /fulfillments/0/tracking must be boolean
- /fulfillments/0/end/location/address must have required property 'country'
- /fulfillments/0/end/contact/email must match format "email"

**/confirm**

- gps coordinates can't be empty
- settlement details should be provided in /confirm
- payment object should be according to CoD (as a part of B2B MVP)

**/on_confirm**

- items[0].fulfillment_id mismatches for Item ITM05775 in /on_select and /on_confirm
- invoice can't be provided when order state is still "Created"

@rapidor

**Comment by BLR-0118** [comment]
1. /on_search:
- location.area_code is missing (I remember seeing it in earlier logs);
2. /on_select, /on_select_non_serviceable:
- error code 30009 means buyer location not serviceable. In this case, buyer should select different fulfillment location & send search request again;
- transaction id for both select requests should be the same but message id should be different;
- this is documented in flow 2 of test cases;
3. same flow as 2 should be shown for item out of stock;
4. /init:
- billing.created_at, updated_at timestamp should match Context.timestamp;
5. /on_confirm:
- fulfillment."@ondc/org/provider_name" was "Rapidor" in on_select but empty in on_confirm;
6. /on_status:
- pickup time (fulfillment.start.time.timestamp) is provided even though fulfillment state hasn't yet reached "Order-picked-up";
- need to see fulfillment status up to order delivery;
7. do you support merchant cancel (unsolicited /on_cancel)?
8. how is payment status updated so that buyer app is aware?

**Comment by BLR-0118** [comment]
@rapidor

**Comment by bluecypher** [comment]
## Flow 2

**/search**

- context/core_version is invalid (should be "version")

**/on_search**

- serviceability construct is missing in /providers/tags

**/select**

- /context/domain must be the nic code for retail (nic2004:52110) from /select onwards
- core_version must be 1.1.0
- city code should not change in /search and /select onwards

**/on_init**

- billing/tax_number is missing (should be the same as in /init)

**/confirm**

- payment/collected_by should be BPP
- payment/params/transaction_id is generated upon successful payment txn (should not be present in /confirm in case of CoD)

## Flow 4

- similar issues as Flow 1

**/on_status_delivered**

- pickup time (/fulfillments/start/time/timestamp) cannot change (should remain the same as when fulfillment state= Order_picked_up)


@rapidor

**Comment by bluecypher** [comment]
## Flow 2

**/on_init**

- tax_number is missing in /on_init (should be the same as in /init)

**/confirm**
- order/created_at timestamp should be the same as context/timestamp

## Flow 4

**/on_status**

- payment/params/transaction_id is mandatory in /on_status_delivered
- payment/collected_by should be BPP
- pickup time (/fulfillments/start/time/timestamp) cannot change (should remain the same as when fulfillment state= Order_picked_up), pickup time is different in /on_status_delivered and /on_status_out_for_delivery


@rapidor

**Comment by bluecypher** [comment]
**/confirm**
- billing object should remain same from /init onwards (tax_number is missing)
- @ondc/org/item_quantity is not required for tax and delivery charges in quote/breakup

**/on_status (delivered)**
- delivery time (/fulfillments/end/timestamp) and updated_at timestamp must match context/timestamp


@rapidor

**Comment by BLR-0118** [comment]
logs cleared for B2B
@rapidor
